name: PHP CI

on:
  push:
    branches:
      - master
      - add-sbom-generation

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  php-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Validate PHP syntax
        run: |
          find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l