name: Security Scan

on:
  push:
    branches:
      - master
      - add-sbom-generation

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: p/php
